### ISSUE TITLE
qsimcirq fails when it encounters measurement gates

### ISSUE THREAD

**Issue by karlunho** [quantumlib/qsim#117]
If a Cirq circuit is passed into qsim with measurement at the end of the circuit, qsim fails to recognize the measurement gate. If the measurement gates are removed, then the everything works.

**Program:**

q0 = cirq.GridQubit(0, 0)
q1 = cirq.GridQubit(1, 0)

def basic_circuit(meas=True):
    sqrt_x = cirq.X**0.5
    yield sqrt_x(q0), sqrt_x(q1)
    yield cirq.CZ(q0, q1)
    yield sqrt_x(q0), sqrt_x(q1)
    if meas:
        yield cirq.measure(q0, key='q0'), cirq.measure(q1, key='q1')

circuit = cirq.Circuit()
circuit.append(basic_circuit())

print("Ciruit:")
print(circuit)

from cirq import Simulator
simulator = Simulator()

waveFunctionResult = simulator.simulate(circuit)

print("Results:")
print(waveFunctionResult)

print(np.around(waveFunctionResult.final_state, 3))

#probabilityAmplitudeResults = simulator.compute_amplitudes(program = circuit, bitstrings=['00', '01', '10', '11'])
#print("Probability Results:")
#print(probabilityAmplitudeResults)

import qsimcirq

qsim_circuit = qsimcirq.QSimCircuit(cirq_circuit=circuit)

qsimulator = qsimcirq.QSimSimulator()

qsim_result = qsimulator.simulate(program = qsim_circuit)

#qsim_result = qsimulator.compute_amplitudes(program = qsim_circuit,
#                                  bitstrings=['00', '01', '10', '11'])

print("Results:")
print(qsim_result)

**Output :**

Ciruit:
(0, 0): ───X^0.5───@───X^0.5───M('q0')───
                   │
(1, 0): ───X^0.5───@───X^0.5───M('q1')───
Results:
measurements: q0=0 q1=0
output vector: |00⟩
[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-48-ec4951b770cc> in <module>()
     41 qsimulator = qsimcirq.QSimSimulator()
     42 
---> 43 qsim_result = qsimulator.simulate(program = qsim_circuit)
     44 
     45 #qsim_result = qsimulator.compute_amplitudes(program = qsim_circuit,

2 frames
/usr/local/lib/python3.6/dist-packages/qsimcirq/qsim_circuit.py in translate_cirq_to_qsim(self, qubit_order)
    130           qsim_gate = "id2"
    131         else:
--> 132           raise ValueError("{!r} No translation for ".format(op))
    133 
    134         # The moment is missing

ValueError: cirq.MeasurementGate(1, 'q0', ()).on(cirq.GridQubit(0, 0)) No translation for

**Comment by 95-martin-orion** [comment]
For terminal measurements, simply omitting the measure operation should be sufficient; however, intermediate measurements will require some changes in core qsim behavior.

See also: #101

**Comment by karlunho** [comment]
Will add this feature once qsim supports measurement gates.
