### ISSUE TITLE
qsimcirq needs better documenation support for "compute_amplitudes"

### ISSUE THREAD

**Issue by karlunho** [quantumlib/qsim#118]
The function "compute_amplitudes" does not exist in the Cirq simulator interface, so it doesn't really make sense for the qsimcirq API to support this function. We should either add "compute_amplitudes" to the cirq simulator interface or remove this function for now.

**Comment by 95-martin-orion** [comment]
The `SimulatesAmplitudes` interface has this method:
https://github.com/quantumlib/Cirq/blob/eb4ad794a9213c20c800fa59199a29f353ca7994/cirq/sim/simulator.py#L126

That said, it does recommend implementing "compute_amplitudes_sweep" instead - we may want to shift to that method.

**Comment by karlunho** [comment]
Qsimcirq simulator should API documentation on what is supported.

**Comment by 95-martin-orion** [comment]
This documentation will be available in the upcoming devsite.

**Comment by 95-martin-orion** [comment]
Duplicate of #120
