### ISSUE TITLE
Need some more documentation on how QSimulator.compute_amplitudes work

### ISSUE THREAD

**Issue by karlunho** [quantumlib/qsim#120]
It isn't clear from the documentation on how QSimulator.compute_amplitudes work. 

When I run a short program, this is what I get:

**Output:**

Circuit:
(0, 0): ───X^0.5───@───X^0.5───
                   │
(1, 0): ───X^0.5───@───X^0.5───
Results:
measurements: (no measurements)
output vector: 0.5|00⟩ + 0.5j|01⟩ + 0.5j|10⟩ + 0.5|11⟩
[0.5+0.j  0. +0.5j 0. +0.5j 0.5+0.j ]
Results:
measurements: (no measurements)
output vector: 0.5|00⟩ + 0.5j|01⟩ + 0.5j|10⟩ + 0.5|11⟩
Probability Amplitudes:
[(0.5+0j), 0.5j, 0.5j, (0.5+0j)]

**Comment by 95-martin-orion** [comment]
@karlunho, what is the distinction between this and #118? Do the API docs in the devsite clarify this sufficiently?

**Comment by 95-martin-orion** [comment]
Resolved with the polished API docs on the devsite.
