### ISSUE TITLE
Add Measurement Gates into qsim

### ISSUE THREAD

**Issue by karlunho** [quantumlib/qsim#130]

**Comment by 95-martin-orion** [comment]
PR #141 resolved this for the C++ side of qsim; I'll investigate what additional work/testing is needed on the Python side, if any.

**Comment by 95-martin-orion** [comment]
Correction: some additional work is required in both qsim and qsimcirq to support surfacing measurement results to users.

In Cirq, measurements are represented as a map from measurement key (usually an identifiable string) to vectors of results (binary values for qubits, and larger int types for qudits). If the current result objects are preserved and a method is provided to query them, that should be sufficient for the purposes of qsimcirq.

**Comment by 95-martin-orion** [comment]
Fixed in PRs #162 and #167.
