### ISSUE TITLE
Support converting circuits to unitary format

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/qsim#132]
For users interested in analyzing circuit unitaries, we should provide the ability to convert an N-qubit circuit to its 2^N x 2^N unitary form. This is required for feature parity with the TFQ variant of qsim.

**Comment by MichaelBroughton** [comment]
Yes, how do we feel about putting in a small standalone module like this in the repo here ? 
https://github.com/tensorflow/quantum/blob/master/tensorflow_quantum/core/qsim/unitary_space_slow.cc

**Comment by MichaelBroughton** [comment]
This has been finished here: #161
