### ISSUE TITLE
Put For in qsim namespace

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/qsim#133]
The "For" object in formux.h is in the global namespace, which may cause collisions with user libraries. It should be folded under the qsim namespace.

**Comment by sergeisakov** [comment]
The "For" object in formux.h is in the qsim namespace.

**Comment by 95-martin-orion** [comment]
My mistake - I likely misread one of the "For" templates as the actual For object (with no "qsim::" qualifier). No changes needed.
