### ISSUE TITLE
Surface gates_cirq in qsimcirq interface

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/qsim#134]
There are currently a bunch of gates that core qsim supports in `gates_cirq.h` that are not being translated from Cirq. We need to surface this support so that users have access to it.

**Comment by 95-martin-orion** [comment]
Because the translation layer currently converts Cirq circuits to input files, this change forces us to make a decision:

1. Keep the current translation behavior, and add all new gates to the input file format.
2. Modify translation to produce qsim gate objects directly, and leave the input file format alone.

Option 1 is less work, but greatly increases the input file complexity and requires greater long-term effort to maintain the input file format.

Option 2 entails deprecation (but not removal) of the input file use case: future users will need to construct circuits in code or with Cirq to use gates outside the `gates_qsim` set. However, this is unavoidable for users who inject their own gate sets.

**Comment by sboixo** [comment]
I think option 2 fits better with the philosophy that qsim is a library and cirq is the frontend to build circuits. Cirq can use the qsim library.

**Comment by karlunho** [comment]
+1 on @sboixo suggestion
