### ISSUE TITLE
[Question]: Cycle count for Simulation functions

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/qsim#147]
inside of `simulator_sse` and `simlator_avx` the worker functions we have are:
```C++
auto f = [](unsigned n, unsigned m, uint64_t i,
                uint64_t sizek, uint64_t mask0, uint64_t mask1,
                const fp_type* matrix, fp_type* rstate)
```
Which then gets called in a parallel manner. Do we have any idea how many CPU cycles or nanoseconds this function needs in order to finish executing once ?

```C++
start = time()
f(...)
end = time()
```
What is `end-start` roughly equal to ?

**Comment by sergeisakov** [comment]
If there are no cache misses and branch mispredictions then it typically takes from 46 to 52 CPU cycles to execute `f` once in `ApplyGate2HH` in `simlator_avx` and from 76 to 88 CPU cycles in `ApplyGate2HH` in `simulator_sse`. Those worker functions have to be inlined.

**Comment by MichaelBroughton** [comment]
Thx!
