### ISSUE TITLE
Support for tcmalloc.

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/qsim#151]
Cloud colab for most of google uses tcmalloc instead of regular malloc. TFQ needs to be reliable under both. When running msan and asan tests for qsim, would it be possible to add a second pair of msan and asan tests where we run under `LD_PRELOAD ... libtcmalloc.so4 (or whatever it is)` ?

**Comment by 95-martin-orion** [comment]
I believe we can add another build config to our `.bazelrc` to support this. It's important to note, however, that CI testing for qsim does not currently include the *SAN tests (although I don't think anything would stop us from adding them to `bazeltest.yml`).
