### ISSUE TITLE
Attempt to decompose Cirq gates

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/qsim#183]
It would be nice if the qsim Cirq simulator tried to decompose gates it doesn't support into gates that it does, so that more general circuits can be passed directly to it. Is this a reasonable feature to add?

**Comment by 95-martin-orion** [comment]
The qsimcirq interface should already decompose unknown gates to those supported by qsim:
https://github.com/quantumlib/qsim/blob/cb2b29e54ce7ccf3604465ef15f22837fc52585d/qsimcirq/qsim_circuit.py#L158-L161

There are a couple of cases where this is known **not** to work - some discussion of this is in #163. `ControlledGate`s are a notable example of this.

**Comment by kevinsung** [comment]
Ah I was running an old version of qsimcirq. Oops. Thanks!
