### ISSUE TITLE
q32d14 tutorial crashes with OOM

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/qsim#249]
Possibly related to #245 - we don't have tests that explicitly check whether this notebook can run. Currently re-running to see if I can find the specs of the Colab instance this ran on.

Sergei, could this indicate a difference in memory usage between the multi-qubit fuser and the basic fuser, even with `f=2`?

**Comment by 95-martin-orion** [comment]
Error message: `tcmalloc: large alloc 34359738368 bytes == 0x5d32000`

**Comment by sergeisakov** [comment]
I think this is not a bug. The state vector size for 32 qubits is exactly 34359738368 bytes (32 GB). So it seems there is no enough memory for the state vector. The multi-qubit fuser uses more memory than the basic fuser in general but it should not be an issue here.

**Comment by 95-martin-orion** [comment]
The bug here is the crashing tutorial. I was concerned it might highlight deeper issues, but if that's not the case then we probably need to replace the notebook with something less resource-intensive (e.g. q30d14 instead of q32d14).

CC'ing @jrossthomson in case we need to make that changeover.

**Comment by jrossthomson** [comment]
Is it failing on the  n2-standard-16? There should be 64GB available.

**Comment by 95-martin-orion** [comment]
> Is it failing on the n2-standard-16? There should be 64GB available.

I apologize, I had forgotten the intended usage of this tutorial. As stated at the top of the doc, it's not expected to survive in a default Google Colab kernel. Closing this as expected behavior.
