### ISSUE TITLE
Multi qubit gate support for unitary

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/qsim#263]
In order to have full support for multi qubit control gates in tensorflow quantum, we need to be able to use multi qubit control gates in the unitary calculator: https://github.com/quantumlib/qsim/blob/master/lib/unitary_calculator_basic.h#L112 . Which is blocking us on: https://github.com/tensorflow/quantum/issues/422 .  It looks like now all of the gate application logic in `simulator_***.cc` is generated by code that writes these C++ functions now so it would be pretty hard for a human being to implement this in a consistent fashion without the scripts mentioned here #227 . @sergeisakov would you be able to implement the logic for multi qubit controlled gate application for the unitary calculator ?

**Comment by sergeisakov** [comment]
Yes, all of the gate application logic in `simulator_***.cc` is generated by a script. However, it doesn't have to be generated by a script. A generic version can be provided (with some performance loss for AVX* and perhaps for SSE) or function templates can be used (without performance loss). Code generation really makes sense only for AVX and AVX512 versions of the simulator. The unitary calculator has only a basic implementation and a generic multi-qubit gate application logic can be written by a human being without a script. I think I'm not the right person to do that.

**Comment by MichaelBroughton** [comment]
> I think I'm not the right person to do that.

So as somebody who helps maintain this repo and is responsible for most of the major contributions by far, you think you aren't the person to do it :P ?

Either way, I can probably struggle my way through implementing this, if you really don't want to at any point. Would we prefer to do that instead ?
