### ISSUE TITLE
Ensure 1:1 parity with Cirq channels

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/qsim#288]
In order to make life easier for qsimcirq translations and TFQ translations, would it be possible to implement kraus operators / channels that have one to one functionality with Cirq ?

In python I can just do something like:

```python3
noisy_op = cirq.depolarize(0.001)(qubit)
```
and then place it inside of my circuit.

In qsim I can construct channels and kraus ops but it looks like I have to do things kind of by hand with "custom" gates. It would be nice to instead just do:

```C++
auto noisy_op = Depolarizing<>::Create(...)
```
Much like we do with Cirq's gates in `cirq_gates.h`.

**Comment by 95-martin-orion** [comment]
+1 - this seems like a nice feature to support our C++ qsim users.

In the meantime, Mike, you can take a look at our Cirq-to-qsim translations in PR #287. In particular:
- `translate_cirq_to_qtrajectory` in `qsim_circuit.py`
    - Extracts the key features of channels and mixtures, then sends them to `add_channel`
- `add_channel` in `pybind_main.cc`
    - Converts the features from `translate_cirq_to_qtrajectory` into a qsim Channel object

If you need a temporary workaround, you could duplicate portions of those methods for the necessary behavior.

**Comment by MichaelBroughton** [comment]
Thx. Left a few general comments on things. I think in our case it'd be worth waiting for a a nice way to create the 1:1 Cirq channels and get this solved. Doing the workarounds on gates back in the day and then moving onto `cirq_gates.h` once they were added wasn't a ton of fun so I think we might wait until this is in, we're in no rush on this feature for TFQ until there's a clean way to do it :)
