### ISSUE TITLE
ParamResolver constructed with 0 and 1 values raises IndexError when fed to simulate

### ISSUE THREAD

**Issue by Wuggins** [quantumlib/qsim#296]
I'm happy to provide a minimal example if it would be helpful, but the issue is simple to describe. When a ParamResolver is constructed with parameters that take only the values 0 and 1 simulate fails with the following kind of error message:

```
~/Projects/vqe_test/tomography.py in evaluate_multi_partition(circuits, qubits, simulate_single_precision)
     68       print(resolvers)
     69       print(circuit)
---> 70       results = simulator.simulate_sweep(
     71         circuit, params=resolvers)
     72 

~/Projects/vqe_test/additional_libraries/qsim/qsimcirq/qsim_simulator.py in simulate_sweep(self, program, params, qubit_order, initial_state)
    356       solved_circuit = protocols.resolve_parameters(program, prs)
    357       translator_fn = getattr(solved_circuit, translator_fn_name)
--> 358       options['c'] = translator_fn(qubit_order)
    359       options['s'] = self.get_seed()
    360       options['n'] = num_qubits

~/Projects/vqe_test/additional_libraries/qsim/qsimcirq/qsim_circuit.py in translate_cirq_to_qsim(self, qubit_order)
    304           time = time_offset + gi
    305           gate_kind = _cirq_gate_kind(qsim_op.gate)
--> 306           add_op_to_circuit(qsim_op, time, qubit_to_index_dict, qsim_circuit)
    307       time_offset += moment_length
    308 

~/Projects/vqe_test/additional_libraries/qsim/qsimcirq/qsim_circuit.py in add_op_to_circuit(qsim_op, time, qubit_to_index_dict, circuit)
    221     }
    222     if isinstance(circuit, qsim.Circuit):
--> 223       qsim.add_gate(gate_kind, time, qsim_qubits, params, circuit)
    224     else:
    225       qsim.add_gate_channel(gate_kind, time, qsim_qubits, params, circuit)

IndexError: map::at
```

I determined that this issue can be fixed by casting the 0 and 1 values of my parameters to int before constructing the ParamResolver, suggesting that the problem is caused by qsim interpreting them as booleans. Cirq's simulator does not have this issue. It would be nice to include either a type check or a cast, or at least a more informative error, so that users don't run into this in the future.

**Comment by 95-martin-orion** [comment]
I'm unable to reproduce this error with the following code:
```
  q0 = cirq.LineQubit(0)
  x, y = sympy.Symbol('x'), sympy.Symbol('y')
  circuit = cirq.Circuit(cirq.X(q0) ** x, cirq.H(q0) ** y)
  prs = [{x: False, y: True}, {x: True, y: False}]

  qsim_simulator = qsimcirq.QSimSimulator()
  qsim_result = qsim_simulator.simulate_sweep(circuit, params=prs)
```
Could you provide the code snippet that produced this error? `IndexError: map::at` suggests that some parameters in your circuit were not specified in one or more parameterizations provided; for instance, I _can_ reproduce the error by removing `y: False` from the second parameterization above.

**Comment by Wuggins** [comment]
Hi Orion,

I was right that it was a type issue but it was more subtle than that. This code produces the error:

```
  q0 = cirq.LineQubit(0)
  x, y = sympy.Symbol('x'), sympy.Symbol('y')
  circuit = cirq.Circuit(cirq.X(q0) ** x, cirq.H(q0) ** y)
  prs = [{x: False, y: True}, {x: True, y: False}]

  qsim_simulator = qsimcirq.QSimSimulator()
  qsim_result = qsim_simulator.simulate_sweep(circuit, params=prs)
```

I don't know if we want to cast np.int64 to int (even with some checking to make sure that the value is in a suitable range) but it would be great to at least raise an informative error.

**Comment by 95-martin-orion** [comment]
I can reproduce the error with that snippet - and this check is almost certainly responsible:
https://github.com/quantumlib/qsim/blob/d1f7680b0ffc30e320ea060aac924c32ba35a802/qsimcirq/qsim_circuit.py#L218-L221

IIRC, Cirq has some workarounds for this in its ParamResolver code. I'll try to apply the same fix here.
