### ISSUE TITLE
[Feature] Support "uncomputing" a particular trajectory

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/qsim#309]
For features in TFQ we rely on the ability to uncompute from the final state of a circuit back to the |00...> state. Would it be possible for the trajectory API in qsim to provide enough information to the users so that they could easily uncompute from a particular final state in a trajectory back to the |00...> state @sergeisakov ?

**Comment by sergeisakov** [comment]
The trajectory API provides such information. The quantum trajectory simulator can collect the indices of sampled Kraus operators. This information can be used to uncompute from the final state back to the initial state. For mixtures, this can be done roughly as follows.

```C++
QuantumTrajectorySimulator::Parameter param;
param.collect_kop_stat = true;

std::vector<uint64_t> stat;

...

// Run one trajectory.
QuantumTrajectorySimulator::Run(param, num_qubits, ncircuit, 0, scratch, state, stat));

...

// Uncompute the final state.
for (std::size_t i = 0; i < ncircuit.size(); ++i) {
  auto k = ncircuit.size() - 1 - i;

  const auto& ops = ncircuit[k][stat[k]].ops;

  for (auto it = ops.rbegin(); it != ops.rend(); ++it) {
    ApplyGateDagger(simulator, *it, state);
  }
}

```

Note this doesn't work for general channels as one needs to use inverse channel matrices.

**Comment by 95-martin-orion** [comment]
@MichaelBroughton, does the behavior demonstrated in #310 resolve this issue?

**Comment by MichaelBroughton** [comment]
Yes, I was hoping to have a method that works for the general channel case, but I guess no luck.
