### ISSUE TITLE
Use wheels in pypi packaging

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/qsim#313]
The goal of this issue is to resolve #242 and #259.

Currently, `pip install qsimcirq` requires building qsim locally. This is fine for Linux, but (as seen in the issues above) often encounters difficulty on MacOS and Windows. In order to resolve this, we need to replace the current packaging with a portable wheel as described by [PEP 513](https://www.python.org/dev/peps/pep-0513/).

**Comment by 95-martin-orion** [comment]
Comment from @Strilanc: cross-platform wheels may be tricky. Consider looking into `cibuildwheel`, which is how [Stim](https://github.com/quantumlib/Stim) builds for Mac and Windows.

**Comment by Strilanc** [comment]
Stim doesn't use cibuildwheels to make the wheels, it uses cibuildwheels to verify that the source compiles on other platforms. You *can* use it to build the wheels, but I'm not confident they will generalize beyond the build machines when AVX instructions are involved.

**Comment by 95-martin-orion** [comment]
This has been resolved.
