### ISSUE TITLE
Setting qubit_order to reverse(qubit_list) doesn't work for QSimSimulator

### ISSUE THREAD

**Issue by verult** [quantumlib/qsim#323]
Running the following

```python
q0, q1 = cirq.LineQubit.range(2)

circuit = cirq.Circuit(
    cirq.H(q0), cirq.H(q1),
)
qsim_simulator = qsimcirq.QSimSimulator()
results = qsim_simulator.simulate(circuit, qubit_order=reversed([q1, q0]))
```
yields `ValueError: Unexpected extra qubits: {cirq.LineQubit(0), cirq.LineQubit(1)}.` However `list(reversed([q1, q0]))` works. An Iterable type isn't handled correctly for some reason it seems like.

Not wrapping it in a `list()` works for `cirq.Simulator()` and `cirq.DensityMatrixSimulator()`.

The expected type for `qubit_order` is `cirq.ops.QubitOrderOrList`, which is
```
QubitOrderOrList = Union[
    cirq.ops.QubitOrder,
    collections.abc.Iterable[cirq.ops.Qid]
]
```
so any Iterable on qubits *should* work.

The only difference I can tell so far between cirq simulators and QSimSimulator is that cirq simulators call `as_qubit_order()` twice:
https://github.com/quantumlib/Cirq/blob/574652c9defe87541ee2a8725d8d09da544b5ed7/cirq-core/cirq/sim/simulator.py#L425
then
https://github.com/quantumlib/Cirq/blob/574652c9defe87541ee2a8725d8d09da544b5ed7/cirq-core/cirq/sim/simulator.py#L536

but that shouldn't have done anything...
https://github.com/quantumlib/Cirq/blob/574652c9defe87541ee2a8725d8d09da544b5ed7/cirq-core/cirq/ops/qubit_order.py#L123

**Comment by 95-martin-orion** [comment]
The root cause appears to be a reuse of `qubit_order` in some of the simulator methods:
https://github.com/quantumlib/qsim/blob/53e694721b0c112956a2ab7cd7f5d235d3973a3b/qsimcirq/qsim_simulator.py#L359-L361
...which will fail if the `qubit_order` provided is an iterable. I'll have a PR out with the fix shortly.
