### ISSUE TITLE
Format python code with black?

### ISSUE THREAD

**Issue by maffoo** [quantumlib/qsim#328]
The qsimcirq code looks like it follows internal google formatting style (two-space indent is a dead giveaway :-) ). I think it would be nice to use [black](https://github.com/psf/black) for formatting to be consistent with other open source projects, such as cirq itself (see https://github.com/quantumlib/Cirq/blob/master/check/format-incremental#L127). Setting up some infrastructure for autoformat the code and check it with a github action would also be nice. Does this make sense?

**Comment by 95-martin-orion** [comment]
Reopening to also track adding CI tests for python format.
