### ISSUE TITLE
cirq.IdentityGate only supported up to 6 qubits

### ISSUE THREAD

**Issue by maffoo** [quantumlib/qsim#330]
Seems like we should be able to support identity gates of any size by treating them as "no-ops".

**Comment by 95-martin-orion** [comment]
This is easy enough to implement - we can just remove the explicit identity conversion rule:
https://github.com/quantumlib/qsim/blob/795293072ef0f5f6b2bc099e94c5080c5e22473d/qsimcirq/qsim_circuit.py#L34-L43

This will fall back on the decompose behavior for `IdentityGate`, which produces no-ops.

**Comment by 95-martin-orion** [comment]
One issue with decomposing to no-ops, related to #327: if an identity gate is the only gate on any qubits, they will be ignored in the results. I'll look into fixing that issue before making this change.

**Comment by maffoo** [comment]
Should be ok if we look at `circuit.all_qubits()` _before_ decomposing. Or, could do a custom decomposition into single-qubit identities here.
