### ISSUE TITLE
New Features for qsim

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/qsim#39]
Some nice features to have for qsim might be:
1. The ability to compute inner products between two state objects.
2. The ability to actually draw X number of bitstring samples from a state object.

**Comment by 95-martin-orion** [comment]
In particular, item (2) is high priority for the qsim-Cirq interface as well. Given that it's a requirement for both TFQ and Cirq, the implementation should live in the C++ code.

**Comment by sergeisakov** [comment]
Cirq doesn't have the ability to sample from a state, does it? I have some code for sampling. I'll add it.

**Comment by 95-martin-orion** [comment]
Cirq does have code for sampling from a state, but for usability I think it makes sense for qsim to provide this behavior directly. Thanks for looking into it.

**Comment by 95-martin-orion** [comment]
> Cirq doesn't have the ability to sample from a state, does it? I have some code for sampling. I'll add it.

@sergeisakov, do you have an update on this? I'm starting to hit this requirement on non-TFQ integration work.

**Comment by MichaelBroughton** [comment]
If you want you can copy the sampling code in TFQ to keep things moving and then improve it when a faster implementation comes along

https://github.com/tensorflow/quantum/blob/master/tensorflow_quantum/core/qsim/state_space.h#L55

Just a thought :)

**Comment by 95-martin-orion** [comment]
The features discussed here are now available in core qsim. #65 tracks adding explicit sampling support in qsimcirq.
