### ISSUE TITLE
QSimSimulator: Can't access final state or set initial state

### ISSUE THREAD

**Issue by gecrooks** [quantumlib/qsim#40]
https://github.com/quantumlib/qsim/blob/24a9af400c3d9e4aac011cb8e5dc6b9e1ac4233b/qsimcirq/qsim_simulator.py#L25

1. The dostring states "This method returns a result which allows access to the entire wave function". But it doesn't really. The returned `SimulationTrialResult` hides the final state in a private `_final_simulator_state` variable.

2. The array returned in `SimulationTrialResult._final_simulator_state` seems to be too large by a factor of 2, as if a qubit is being added somewhere.

3. The object in `SimulationTrialResult._final_simulator_state` is a numpy array, which causes `SimulationTrialResult.qubit_map` to fail.

4. The `initial_state` method parameter is silently ignored. It does does seem possible to set the initial state. 

5. The test `test_cirq_qsim_simulate_fullstate` does not test any properties of the final fullstate.

**Comment by 95-martin-orion** [comment]
See also: [Cirq issue 2755](https://github.com/quantumlib/Cirq/issues/2755)

Other Cirq simulators seem to use the following pattern:

1. Define a "State" wrapper for the final state which has a `qubit_map` property.
2. Create a subclass of `SimulationTrialResult` with a method to expose the state object.
3. Document and test the above classes.

This should resolve items (1), (3), and (5). Regarding (2), IIRC qsim stores its amplitudes as floats (not complex values) which would result in the observed 2x increase in array size. I'll get PRs started to address these.

Item (4) is somewhat of a separate issue: qsim always expects an all-zero input state, but we can add the necessary X gates internally. I'll open a separate issue to track this.

**Comment by gecrooks** [comment]
The amplitude array seems to have qubits in the opposite order than I'd expect from cirq. Something like this is needed.  
```
        amp = res._final_simulator_state
        N = len(qsim_circuit.all_qubits())
        amp = np.reshape(amp, [2]*(N+1))
        amp = np.transpose(amp)
        amp = amp[0] + 1j * amp[1]
        amp = amp.flatten()
```

**Comment by sergeisakov** [comment]
qsim uses the following bitstring qubit order convention: |q_{n-1} ... q_2 q_1 q_0>. If you need |q_0 q_1 q_2 ... q_{n-1}> then it is probably better to reshape the array in C++.
