### ISSUE TITLE
Release v0.10.1 is failing on Windows wheel

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/qsim#407]
[Workflow logs](https://github.com/quantumlib/qsim/actions/runs/1128850232) show that the Windows wheel is failing with this error:
```
  + pip install C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheel32hyxjzh\repaired_wheel\qsimcirq-0.10.1-cp35-cp35m-win_amd64.whl
  DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
  Processing c:\users\runner~1\appdata\local\temp\cibuildwheel32hyxjzh\repaired_wheel\qsimcirq-0.10.1-cp35-cp35m-win_amd64.whl
  Collecting pybind11
    Downloading pybind11-2.7.1-py2.py3-none-any.whl (200 kB)
  ERROR: Could not find a version that satisfies the requirement flynt~=0.60 (from qsimcirq)
  ERROR: No matching distribution found for flynt~=0.60
Error: Command ['pip', 'install', 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\cibuildwheel32hyxjzh\\repaired_wheel\\qsimcirq-0.10.1-cp35-cp35m-win_amd64.whl'] failed with code 1. None
```

@laurynasas any ideas on this? Strictly speaking we shouldn't need `flynt` in the Windows build (it's just for format-checking), so we can drop it if necessary.

**Comment by laurynasas** [comment]
Right, `flynt` and `black` packages are only available with cp36+ so given that we build cp36+ on all other platforms we can remove cp35 wheel from Windows builds as well. Will open PR for that.

**Comment by 95-martin-orion** [comment]
Unfortunately the 0.10.1 release, having been cut before the above PR, is unable to pick up the fix. I'll cut 0.10.2 (after a couple other small changes in the pipeline) to get things moving again.
