### ISSUE TITLE
The version of `qsim` on PyPi breaks with `cirq` v0.13.1

### ISSUE THREAD

**Issue by antalszava** [quantumlib/qsim#465]
After upgrading `cirq` and `qsimcirq`, the following error traceback comes up when running the [measurement sampling example](https://quantumai.google/qsim/tutorials/qsimcirq#measurement_sampling) from the website:
```
~/anaconda3/lib/python3.8/site-packages/qsimcirq/qsim_simulator.py in _sample_measure_results(self, program, repetitions)
    242         for op in measurement_ops:
    243             gate = op.gate
--> 244             key = protocols.measurement_key(gate)
    245             meas_ops[key] = op
    246             if key in bounds:

AttributeError: module 'cirq.protocols' has no attribute 'measurement_key'
```
This issue seems to be related to the [latest release of Cirq](https://github.com/quantumlib/Cirq/releases/tag/v0.13.1) and has been resolved in the development version of `qsim`. Would a release of the `qsim` project to PyPi be coming up soon?

**Comment by 95-martin-orion** [comment]
qsimcirq 0.10.3 has been released with the fix.
