### ISSUE TITLE
Disable gate fusion

### ISSUE THREAD

**Issue by mlazzarin** [quantumlib/qsim#510]
I'm running benchmarks on different quantum simulation libraries, and I'd like to disable gate fusion so that I can decouple the performance of the fusion algorithm with the "raw" performance of the library (without optimizations at circuit level).

I found a way to tweak the maximum size of the fused gates through the ``max_fused_gate_size`` parameter.
Is there a flag to completely deactivate gate fusion?

**Comment by 95-martin-orion** [comment]
@sergeisakov, is this supported at the C++ level? We don't appear to have a specific flag for it in qsimcirq, but it's possible I'm missing some special-case behavior.

**Comment by sergeisakov** [comment]
No, this is not supported at the C++ level. It is not possible to completely deactivate gate fusion.

**Comment by mlazzarin** [comment]
Ok, thank you.
