### ISSUE TITLE
Pip installing qsimcirq downgrades black

### ISSUE THREAD

**Issue by gecrooks** [quantumlib/qsim#514]
When I run `pip install qsimcirq` then my local install of `black` gets downgraded from 22.1.0 to 20.8b1, breaking my local development environment, apparently because qsim has recently added build and test dependencies to `requirements.txt`, and hard coded the black version.

This seems not optimal. Presumable qsim does not have a runtime dependency on black.
 
https://github.com/quantumlib/qsim/blob/f8a205913f7543e0f50b422750a6b013845b8284/requirements.txt#L10

**Comment by 95-martin-orion** [comment]
This should be fixed with #516, as black is no longer in the main `requirements.txt` for qsimcirq.
