### ISSUE TITLE
Compatibility with latest Cirq

### ISSUE THREAD

**Issue by 1tnguyen** [quantumlib/qsim#535]
Cirq v0.15.0 has been released and it seems to be incompatible with the current qsim version (0.12.1).

Is there a plan to release a new qsim version soon?

**Comment by 95-martin-orion** [comment]
Yes, qsim v0.13.0 is slated for release as soon as blocking issues with the macOS build are resolved ([link](https://github.com/quantumlib/qsim/runs/7124424383?check_suite_focus=true)).

**Comment by 1tnguyen** [comment]
Thanks for the information!

**Comment by 95-martin-orion** [comment]
qsimcirq 0.13.0 has been released, and should be compatible with Cirq 0.15.0.

Please open a new issue if problems persist, and thanks for raising this one!
