### ISSUE TITLE
Upgrade for compatibility with Cirq 1.0

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/qsim#543]
Several deprecated parts of Cirq are being removed in preparation for its 1.0 release. In order for qsim to remain compatible, we need to upgrade its behavior to match.

The nightly compatibility check is a useful indicator for what's currently broken.

**Comment by 95-martin-orion** [comment]
Sample nightly compatibility run: [link](https://github.com/quantumlib/qsim/runs/7312352387?check_suite_focus=true)

**Comment by maffoo** [comment]
Fixed by #555.
