### ISSUE TITLE
Bump the Docker image to use Python 3.7 instead of 3.6

### ISSUE THREAD

**Issue by rht** [quantumlib/qsim#551]
Since #549 has been merged, the oldest supported Python version is now 3.7.

**Comment by 95-martin-orion** [comment]
The Docker image auto-updates, but we recently found that its current OS is incompatible with Python > 3.6. I'll switch out the Docker version to get us bumped forward.

**Comment by 95-martin-orion** [comment]
The `jupyter_qsim` docker image used in the Cloud tutorials was updated in #552. If you pull a fresh copy of the image, it will include the latest versions of both qsim and Cirq.

Does this fulfill your requirements?

**Comment by rht** [comment]
Yes, I just pulled, and it is indeed Debian Bullseye, Python 3.9.2, Cirq 0.15.0, qsimcirq 0.13.3. Now I don't have to worry about maintaining compatibility with Python 3.6. Thank you so much, much appreciated!
