### ISSUE TITLE
Installing qsimcirq~=0.14.0 on Python Docker image tagged 3.10-alpine failed

### ISSUE THREAD

**Issue by rht** [quantumlib/qsim#567]
```
ERROR: Could not find a version that satisfies the requirement qsimcirq~=0.14.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4.dev202006030832, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.9.2, 0.9.5, 0.10.0.dev20210623)
ERROR: No matching distribution found for qsimcirq~=0.14.0
```

I suppose this is because the more recent wheels don't support Alpine's `musl`?

**Comment by rht** [comment]
https://github.com/docker-library/python/issues/341#issuecomment-426026398

**Comment by rht** [comment]
Based on reading the thread above, it looks like this issue can't be resolved?

**Comment by 95-martin-orion** [comment]
This looks similar to #537, which tells me your guess about `musl` is likely correct. I vaguely remember running up against the `manylinux` vs. `musllinux` issue there.

@pavoljuhas, could you investigate whether it is possible to add a `musl` wheel to our release?

**Comment by pavoljuhas** [comment]
The [cibuildwheel](https://github.com/pypa/cibuildwheel#what-does-it-do) which we use should be in theory capable of producing *musllinux* wheels.  To be worth the effort, we need to make sure that qsimcirq dependencies can be installed on a musl-based system as well.

@rht - can you please check if you can install all packages from qsim [requirements.txt](https://github.com/quantumlib/qsim/blob/master/requirements.txt)?

```
$ pip install -r requirements.txt
```

**Comment by rht** [comment]
I tested on
```
absl-py
cirq-core~=1.0
numpy~=1.16
pybind11
typing_extensions
```
and found out that Numpy doesn't support `musl` yet: https://github.com/numpy/numpy/issues/20089. There were 19 test errors when they tested the `musllinux` wheel.

**Comment by pavoljuhas** [comment]
I suppose this is a no go at this time.  Feel free to reopen when numpy wheels are available for musllinux.

**Comment by rht** [comment]
OK, thank you. I will let you guys know once that Numpy issue is closed and the wheel has made it into a release.
