### ISSUE TITLE
Inconsistent versions

### ISSUE THREAD

**Issue by gecrooks** [quantumlib/qsim#57]
The version string in setup.py is currently '0.0.1',

https://github.com/quantumlib/qsim/blob/cb02f33c9882da81ce09e1ae043b7fd5ed277c41/setup.py#L79

but pypi thinks the latest version is '0.0.2'

https://pypi.org/project/qsimcirq/0.0.2/

Also, it would be useful for qsimcirq to have a version attribute `__version__` for programatic access. This does not currently work...

```
> python -c 'import qsimcirq; print(qsimcirq.__version__)'
```

**Comment by 95-martin-orion** [comment]
While this issue is raised, we should also add a doc for how to perform the release process - including permissions required and any extra tests above and beyond the CI suite that should be run.

@iamvamsikrishnad, could you look into this? If I understand correctly, getting the versions to match will require a new release (i.e. v0.0.3).

**Comment by gecrooks** [comment]
Another tangentially related issue is that qsim is currently locked to version 0.6 of cirq, but AFAICT everything works just fine with the latest 0.7 cirq.

https://github.com/quantumlib/qsim/blob/cb02f33c9882da81ce09e1ae043b7fd5ed277c41/requirements.txt#L3

**Comment by iamvamsikrishnad** [comment]
> While this issue is raised, we should also add a doc for how to perform the release process - including permissions required and any extra tests above and beyond the CI suite that should be run.
> 
> @iamvamsikrishnad, could you look into this? If I understand correctly, getting the versions to match will require a new release (i.e. v0.0.3).

I created a seperate issue for the doc.

**Comment by 95-martin-orion** [comment]
These are now consistent at `0.0.2` - further work is tracked in #59.
