### ISSUE TITLE
add a doc for how to perform the release process - including permissions required and any extra tests above and beyond the CI suite that should be run.

### ISSUE THREAD

**Issue by iamvamsikrishnad** [quantumlib/qsim#59]
While this issue is raised, we should also add a doc for how to perform the release process - including permissions required and any extra tests above and beyond the CI suite that should be run.

@iamvamsikrishnad, could you look into this? If I understand correctly, getting the versions to match will require a new release (i.e. v0.0.3).

_Originally posted by @95-martin-orion in https://github.com/quantumlib/qsim/issues/57#issuecomment-600128199_

**Comment by 95-martin-orion** [comment]
This just came up in #62: as part of the release process, we should have some way to identify what PR the release aligns with. I think Github project releases are the way to do this, but I'm not 100% certain.

**Comment by gecrooks** [comment]
Each release should be tagged, e.g. `git tag v0.04`, so that it shows up on github under releases. (And then remember that git treats tags weirdly, so the tag has to be specifically pushed, which I tend to forget.)

**Comment by 95-martin-orion** [comment]
We've been seeing increased interest in a stable qsim-Cirq interface, so I've picked up this request. So far, I've found a convenient way of constructing a "fire and forget"-style release in Kokoro, the tool we use to test TFQ compatibility. Once that pipeline is built, I'll cut a new release and send out a PR documenting how to trigger it.

**Comment by iamvamsikrishnad** [comment]
Sounds good.

**Comment by 95-martin-orion** [comment]
Version 0.1.0 has been released! We now also have `docs/release-qsimcirq.md` with details on the release process, which is Google-internal. I've left TODOs for myself to add internal docs for this; until then, users are advised to contact me if a release is needed.
