### ISSUE TITLE
`No matching distribution found for qsimcirq==0.15.0` for python 3.11

### ISSUE THREAD

**Issue by vtomole** [quantumlib/qsim#591]
We claim to support[ `>=3.7.0`](https://github.com/quantumlib/qsim/blob/f3d8d373a0bac7900aa1d58bf2c133d6ceb0fe0a/setup.py#L97) but the following happens:
```
vtomole@vtomole:~$ python3.11 -m venv qsim_venv
vtomole@vtomole:~$ source qsim_venv/bin/activate
(qsim_venv) vtomole@vtomole:~$ pip install qsimcirq==0.15.0
ERROR: Could not find a version that satisfies the requirement qsimcirq==0.15.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4.dev202006030832, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.9.2, 0.9.5, 0.10.0.dev20210623)
ERROR: No matching distribution found for qsimcirq==0.15.0
```

**Comment by 95-martin-orion** [comment]
I can confirm that qsim has no py3.11 build:
https://github.com/quantumlib/qsim/blob/f3d8d373a0bac7900aa1d58bf2c133d6ceb0fe0a/.github/workflows/release_wheels.yml#L21-L23

@vtomole, do you have an application that requires using qsim with python 3.11, or would restricting the `python_requires` to supported python versions be sufficient?

**Comment by vtomole** [comment]
Ah, https://github.com/quantumlib/qsim/blob/master/docs/install_qsimcirq.md#linux-installation implicitly says `python 3.11` is not supported: ``We provide `qsimcirq` Python wheels on 64-bit `x86` architectures with `Python 3.{6,7,8,9}`.``

Restricting `python_requires` sounds good. I was just testing how compatible `qsim` was with recent versions of python. The main draw for python 3..11 is the [performance improvements](https://www.phoronix.com/review/python-311-performance). But again, it was released relatively recently so no there is no rush in supporting it.
