### ISSUE TITLE
Release v0.0.3 

### ISSUE THREAD

**Issue by iamvamsikrishnad** [quantumlib/qsim#64]
That would depend on the most recent PR prior to pushing the qsim PyPI package - I suspect that #43 was not included in that release.

@iamvamsikrishnad, do you know what PR v0.0.2 aligns with? Also, we should consider pushing a release to pick up this and other minor fixes that went in since v0.0.2.

_Originally posted by @95-martin-orion in https://github.com/quantumlib/qsim/issues/62#issuecomment-604050821_

**Comment by 95-martin-orion** [comment]
From the current list of issues, is there anything we should resolve before pushing this release out? Given that our release process is still fairly relaxed, it's probably fine if the answer is "release as-is and push any new urgent fixes in 0.0.4".

**Comment by iamvamsikrishnad** [comment]
I think we can go as is. The only issue I see is #24 which can go in the later version.

**Comment by 95-martin-orion** [comment]
Sounds good to me. For selfish reasons I'd like to make sure #68 is in 0.0.3 as well - it should go in later today.

**Comment by iamvamsikrishnad** [comment]
Done and uploaded to pypi: https://pypi.org/project/qsimcirq/0.0.3/#description
