### ISSUE TITLE
missing py312 wheels

### ISSUE THREAD

**Issue by richrines1** [quantumlib/qsim#655]
qsimcirq 0.20.0 adds support for python 3.12, however the corresponding wheels are [missing](https://pypi.org/project/qsimcirq/0.20.0/#files) from the pypi release so `pip install qsimcirq==0.20.0` still fails on python 3.12

**Comment by NoureldinYosri** [comment]
thanks for reporting this. while we fix this you can install qsimcirq directly from github `pip install git+https://github.com/quantumlib/qsim`
