### ISSUE TITLE
Missing arm64 wheels for MacOS on PyPi

### ISSUE THREAD

**Issue by chriseclectic** [quantumlib/qsim#676]
Trying to pip install `qsimcirq` on an M3 Macbook fails while attempting to install a very old version (0.9.5). It looks like this is due to missing arm64 wheels on pypi.

Running `pip install qsimcirq==0.21` gives
```
ERROR: Could not find a version that satisfies the requirement qsimcirq==0.21 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4.dev202006030832, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.9.2, 0.9.5, 0.10.0.dev20210623)
ERROR: No matching distribution found for qsimcirq==0.21
```

- Python Version 3.12
- OS: MacOS 15.1.1

**Comment by 95-martin-orion** [comment]
Hi @chriseclectic! Unfortunately, qsim is not compatible with ARM64 - see discussion on this topic [here](https://github.com/quantumlib/qsim/issues/495#issuecomment-1126317127).

For the reasons described in the link above, adding ARM64 support is not feasible. Closing.
