### ISSUE TITLE
Issues/Fixes for clean build on Centos/gcc 8

### ISSUE THREAD

**Issue by kkissell** [quantumlib/qsim#78]
Pulled from current head and found issues with building under Centos with Gcc 8 and openmp using the makefile (as opposed to make.sh).  Simple fix to the makefile made things buildable to pass all tests, but wanted to suppress the bogus warnings about uninitialized variables as well.  Patch file attached.

[0001-Minor-cleanup-for-clean-make-on-Centos-with-gcc-8.patch.zip](https://github.com/quantumlib/qsim/files/4467076/0001-Minor-cleanup-for-clean-make-on-Centos-with-gcc-8.patch.zip)

**Comment by 95-martin-orion** [comment]
As noted in the PR, tests previously relied on the top-level definition of `CXXFLAGS` to build correctly. It feels a little awkward to redefine those flags, but this has been an issue for enough users that I agree we should make the change.

**Comment by 95-martin-orion** [comment]
Submitted in PR #79.
