### ISSUE TITLE
Error with make

### ISSUE THREAD

**Issue by weiT1993** [quantumlib/qsim#90]
[error_logs.txt](https://github.com/quantumlib/qsim/files/4560162/error_logs.txt)

I am trying to install qsim on a linux machine. I did 
```
mkdir build && cd build && cmake3 ..
```
which successfully ran. However, running
```
make
```
in the root directory produces the above error logs. I am not an experienced C++ user, please bear with me if this is a stupid question. Thank you!

**Comment by 95-martin-orion** [comment]
From the error logs:
```
This file requires compiler and library support for the ISO C++ 2011 standard.
```
Our Makefile assumes that C++11 is enabled - in your case, you can either:
1. Add `-std=c++11` to the `CXXFLAGS` line in the top-level Makefile, or
2. Build using Bazel (the .bazelrc enforces use of C++11).

Hope that helps!

**Comment by weiT1993** [comment]
[error_logs.txt](https://github.com/quantumlib/qsim/files/4560403/error_logs.txt)

Thanks, that gets me through the first errors. But there are other errors appearing now.

**Comment by 95-martin-orion** [comment]
From the file:
```
error: use of deleted function
‘std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)' {...}
```
This is a known error when using older versions of gcc, highlighted in issue #84. Your previous error logs indicate you are using gcc-4.8.2 -- if possible, I would recommend updating your gcc version, as we currently don't plan to support gcc-4.8.x

@sergeisakov, this shows that some subset of users may be using these older gcc versions - should we reconsider adding support for these versions?

**Comment by weiT1993** [comment]
I updated to gcc-8.3.1. However, `make` still produces the following errors:
[error_logs.txt](https://github.com/quantumlib/qsim/files/4560857/error_logs.txt)

**Comment by 95-martin-orion** [comment]
Hmm...that indicates that your system does not use AVX by default. That should be fine, since PR #82 added multiplexing for (AVX|SSE|basic) simulators, but obviously something's not quite right.

You can try replacing `-march=native` in the Makefile with `-mavx2 -mfma`, but if your machine doesn't support AVX then that may fail as well.

@sergeisakov, could you take a look at this? I think the Bazel tests only check the AVX case - we probably should expand them to cover SSE and basic as well.

**Comment by weiT1993** [comment]
I switched to a newer Skylake server and it works now, so I am closing this issue. Thanks!
